In [4]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\Forsan\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\Forsan\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Forsan\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\Forsan\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\Forsan\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in C:\Users\Forsan\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [7]:
import pandas as pd

In [19]:
df = pd.read_csv("C:\\Users\\Forsan\\Desktop\\Projects\\NoonPipeline\\noon-pipeline\\noon-pipeline\\data\\NoonScraping3.csv", index_col=0)

In [20]:
df

,phone,price,link,rating,rating_nums,img,desc,specific,delivery,before_discount,ranking,selling_vendor,payment_info
0,Samsung Galaxy A36 5G Dual SIM Awesome Black 8...,"22,500",https://www.noon.com/egypt-en/galaxy-a36-5g-du...,4.4,1768 Ratings,https://f.nooncdn.com/p/pzsku/ZF8497F284E09C47...,HIGHLIGHTS\nSlimmer Design With A Stylish Twis...,Memory Type No Expandable Memory\nSIM Count Du...,Get it by 12 Oct\nOrder in 20h 56m,NaN,Best Seller #8,NaN,50% off interest from 3-12 months
1,ITEL A200 Plus Dual SIM Comet Orange 3GB RAM 1...,"6,999",https://www.noon.com/egypt-en/a200-plus-dual-s...,4.3,30 Ratings,No image,HIGHLIGHTS\nIP65 dust tight and water resistan...,SIM Count Dual SIM\nBattery Size 6000 mAh\nScr...,Get it Tomorrow\nOrder in 2h 55m,no discount,Explore other bestsellers\nin,NaN,50% off interest from 3-12 months
2,Infinix Smart 20 Dual SIM Polaris Titanium 8GB...,"9,114",https://www.noon.com/egypt-en/smart-20-dual-si...,4.3,625 Ratings,https://f.nooncdn.com/p/pzsku/ZBF9D9A3E6BFB7D4...,The Smart 20 Series delivers reliable everyday...,Memory Type MicroSD\nSIM Count Dual SIM\nRAM S...,Get it Tomorrow\nOrder in 2h 55m,NaN,Best Seller #18,NaN,50% off interest from 3-12 months
3,ITEL A200+ Dual SIM Nightly Blue 3GB RAM 64GB ...,"6,599",https://www.noon.com/egypt-en/a200-dual-sim-ni...,4.3,No rating,https://f.nooncdn.com/p/pzsku/ZEEE29E292DCA47B...,The itel A200+ is designed to deliver a smooth...,SIM Count Dual SIM\nBattery Size 6000 mAh\nScr...,Get it Tomorrow\nOrder in 2h 54m,no discount,Best Seller #3\nin\nSmartphones,Sold by noon,50% off interest from 3-12 months
4,Samsung Galaxy A17 Dual SIM 4G Light Blue 6GB ...,"14,199",https://www.noon.com/egypt-en/galaxy-a17-dual-...,4.4,3520 Ratings,No image,1. Gemini is a trademark of Google LLC. Result...,Secondary Camera Resolution 13 MP\nCPU Speed 1...,Get it Tomorrow\nOrder in 2h 54m,no discount,Best Seller #27\nin\nSmartphones,Sold by noon,50% off interest from 3-12 months
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Apple iPhone 15 128GB Black 5G With FaceTime -...,"49,184",https://www.noon.com/egypt-en/iphone-15-128gb-...,4.6,22469 Ratings,https://f.nooncdn.com/p/pzsku/Z1A1EFC66C4CD0DC...,No description,no specification,Get it by 12 Oct\nOrder in 21h 2m,no discount,Explore other bestsellers\nin\nSmartphones,Sold by Paris store,50% off interest from 3-12 months
96,OPPO A6 Dual SIM 6GB RAM 128GB SAPPHIRE BLUE 4...,"14,740",https://www.noon.com/egypt-en/a6-dual-sim-6gb-...,4.2,24 Ratings,https://f.nooncdn.com/p/pzsku/Z688112374C34976...,No description,no specification,Get it Tomorrow\nOrder in 3h 2m,EGP\n 16000.00,Explore other bestsellers\nin\nSmartphones,Sold by Al basha,50% off interest from 3-12 months
97,Infinix Note 60 AI Dual SIM Rose Gold 16GB(8+8...,"19,299",https://www.noon.com/egypt-en/note-60-ai-dual-...,4.7,38 Ratings,https://f.nooncdn.com/p/pzsku/Z2F4092116F122CB...,No description,no specification,Get it Tomorrow\nOrder in 3h 1m,EGP\n 20999.00,Explore other bestsellers\nin\nSmartphones,Sold by noon,50% off interest from 3-12 months
98,Infinix Hot 70 AI Dual SIM Dive Blue 12GB(6+6)...,"12,907",https://www.noon.com/egypt-en/hot-70-ai-dual-s...,4.3,35 Ratings,https://f.nooncdn.com/p/pzsku/ZA173CCA2A2B2745...,No description,no specification,Get it Tomorrow\nOrder in 3h 1m,EGP\n 14899.00,Explore other bestsellers\nin\nSmartphones,Sold by Masha Brands,50% off interest from 3-12 months
99,NOKIA 3210 Dual SIM Scuba Blue 64MB RAM 128MB ...,"1,300",https://www.noon.com/egypt-en/3210-dual-sim-sc...,3.6,657 Ratings,https://f.nooncdn.com/p/pzsku/ZB15DF0546A1CCB2...,No description,no specification,Get it Tomorrow\nOrder in 3h 1m,no discount,Best Seller #11\nin\nFeature Phones,Sold by AL Bashawat,50% off interest from 3-12 months

In [21]:
df = df.reset_index(drop=True)   # clean 0..n-1 index first
df.index += 1

,phone,price,link,rating,rating_nums,img,desc,specific,delivery,before_discount,ranking,selling_vendor,payment_info
1,Samsung Galaxy A36 5G Dual SIM Awesome Black 8...,"22,500",https://www.noon.com/egypt-en/galaxy-a36-5g-du...,4.4,1768 Ratings,https://f.nooncdn.com/p/pzsku/ZF8497F284E09C47...,HIGHLIGHTS\nSlimmer Design With A Stylish Twis...,Memory Type No Expandable Memory\nSIM Count Du...,Get it by 12 Oct\nOrder in 20h 56m,NaN,Best Seller #8,NaN,50% off interest from 3-12 months
2,ITEL A200 Plus Dual SIM Comet Orange 3GB RAM 1...,"6,999",https://www.noon.com/egypt-en/a200-plus-dual-s...,4.3,30 Ratings,No image,HIGHLIGHTS\nIP65 dust tight and water resistan...,SIM Count Dual SIM\nBattery Size 6000 mAh\nScr...,Get it Tomorrow\nOrder in 2h 55m,no discount,Explore other bestsellers\nin,NaN,50% off interest from 3-12 months
3,Infinix Smart 20 Dual SIM Polaris Titanium 8GB...,"9,114",https://www.noon.com/egypt-en/smart-20-dual-si...,4.3,625 Ratings,https://f.nooncdn.com/p/pzsku/ZBF9D9A3E6BFB7D4...,The Smart 20 Series delivers reliable everyday...,Memory Type MicroSD\nSIM Count Dual SIM\nRAM S...,Get it Tomorrow\nOrder in 2h 55m,NaN,Best Seller #18,NaN,50% off interest from 3-12 months
4,ITEL A200+ Dual SIM Nightly Blue 3GB RAM 64GB ...,"6,599",https://www.noon.com/egypt-en/a200-dual-sim-ni...,4.3,No rating,https://f.nooncdn.com/p/pzsku/ZEEE29E292DCA47B...,The itel A200+ is designed to deliver a smooth...,SIM Count Dual SIM\nBattery Size 6000 mAh\nScr...,Get it Tomorrow\nOrder in 2h 54m,no discount,Best Seller #3\nin\nSmartphones,Sold by noon,50% off interest from 3-12 months
5,Samsung Galaxy A17 Dual SIM 4G Light Blue 6GB ...,"14,199",https://www.noon.com/egypt-en/galaxy-a17-dual-...,4.4,3520 Ratings,No image,1. Gemini is a trademark of Google LLC. Result...,Secondary Camera Resolution 13 MP\nCPU Speed 1...,Get it Tomorrow\nOrder in 2h 54m,no discount,Best Seller #27\nin\nSmartphones,Sold by noon,50% off interest from 3-12 months
...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,Apple iPhone 15 128GB Black 5G With FaceTime -...,"49,184",https://www.noon.com/egypt-en/iphone-15-128gb-...,4.6,22469 Ratings,https://f.nooncdn.com/p/pzsku/Z1A1EFC66C4CD0DC...,No description,no specification,Get it by 12 Oct\nOrder in 21h 2m,no discount,Explore other bestsellers\nin\nSmartphones,Sold by Paris store,50% off interest from 3-12 months
97,OPPO A6 Dual SIM 6GB RAM 128GB SAPPHIRE BLUE 4...,"14,740",https://www.noon.com/egypt-en/a6-dual-sim-6gb-...,4.2,24 Ratings,https://f.nooncdn.com/p/pzsku/Z688112374C34976...,No description,no specification,Get it Tomorrow\nOrder in 3h 2m,EGP\n 16000.00,Explore other bestsellers\nin\nSmartphones,Sold by Al basha,50% off interest from 3-12 months
98,Infinix Note 60 AI Dual SIM Rose Gold 16GB(8+8...,"19,299",https://www.noon.com/egypt-en/note-60-ai-dual-...,4.7,38 Ratings,https://f.nooncdn.com/p/pzsku/Z2F4092116F122CB...,No description,no specification,Get it Tomorrow\nOrder in 3h 1m,EGP\n 20999.00,Explore other bestsellers\nin\nSmartphones,Sold by noon,50% off interest from 3-12 months
99,Infinix Hot 70 AI Dual SIM Dive Blue 12GB(6+6)...,"12,907",https://www.noon.com/egypt-en/hot-70-ai-dual-s...,4.3,35 Ratings,https://f.nooncdn.com/p/pzsku/ZA173CCA2A2B2745...,No description,no specification,Get it Tomorrow\nOrder in 3h 1m,EGP\n 14899.00,Explore other bestsellers\nin\nSmartphones,Sold by Masha Brands,50% off interest from 3-12 months
100,NOKIA 3210 Dual SIM Scuba Blue 64MB RAM 128MB ...,"1,300",https://www.noon.com/egypt-en/3210-dual-sim-sc...,3.6,657 Ratings,https://f.nooncdn.com/p/pzsku/ZB15DF0546A1CCB2...,No description,no specification,Get it Tomorrow\nOrder in 3h 1m,no discount,Best Seller #11\nin\nFeature Phones,Sold by AL Bashawat,50% off interest from 3-12 months

In [23]:
# Display first rows
df.head()

,phone,price,link,rating,rating_nums,img,desc,specific,delivery,before_discount,ranking,selling_vendor,payment_info
1,Samsung Galaxy A36 5G Dual SIM Awesome Black 8...,"22,500",https://www.noon.com/egypt-en/galaxy-a36-5g-du...,4.4,1768 Ratings,https://f.nooncdn.com/p/pzsku/ZF8497F284E09C47...,HIGHLIGHTS\nSlimmer Design With A Stylish Twis...,Memory Type No Expandable Memory\nSIM Count Du...,Get it by 12 Oct\nOrder in 20h 56m,NaN,Best Seller #8,NaN,50% off interest from 3-12 months
2,ITEL A200 Plus Dual SIM Comet Orange 3GB RAM 1...,"6,999",https://www.noon.com/egypt-en/a200-plus-dual-s...,4.3,30 Ratings,No image,HIGHLIGHTS\nIP65 dust tight and water resistan...,SIM Count Dual SIM\nBattery Size 6000 mAh\nScr...,Get it Tomorrow\nOrder in 2h 55m,no discount,Explore other bestsellers\nin,NaN,50% off interest from 3-12 months
3,Infinix Smart 20 Dual SIM Polaris Titanium 8GB...,"9,114",https://www.noon.com/egypt-en/smart-20-dual-si...,4.3,625 Ratings,https://f.nooncdn.com/p/pzsku/ZBF9D9A3E6BFB7D4...,The Smart 20 Series delivers reliable everyday...,Memory Type MicroSD\nSIM Count Dual SIM\nRAM S...,Get it Tomorrow\nOrder in 2h 55m,NaN,Best Seller #18,NaN,50% off interest from 3-12 months
4,ITEL A200+ Dual SIM Nightly Blue 3GB RAM 64GB ...,"6,599",https://www.noon.com/egypt-en/a200-dual-sim-ni...,4.3,No rating,https://f.nooncdn.com/p/pzsku/ZEEE29E292DCA47B...,The itel A200+ is designed to deliver a smooth...,SIM Count Dual SIM\nBattery Size 6000 mAh\nScr...,Get it Tomorrow\nOrder in 2h 54m,no discount,Best Seller #3\nin\nSmartphones,Sold by noon,50% off interest from 3-12 months
5,Samsung Galaxy A17 Dual SIM 4G Light Blue 6GB ...,"14,199",https://www.noon.com/egypt-en/galaxy-a17-dual-...,4.4,3520 Ratings,No image,1. Gemini is a trademark of Google LLC. Result...,Secondary Camera Resolution 13 MP\nCPU Speed 1...,Get it Tomorrow\nOrder in 2h 54m,no discount,Best Seller #27\nin\nSmartphones,Sold by noon,50% off interest from 3-12 months

In [24]:
df.dtypes

phone                  str
price                  str
link                   str
rating             float64
rating_nums            str
img                    str
desc                   str
specific               str
delivery               str
before_discount        str
ranking                str
selling_vendor         str
payment_info           str
dtype: object

In [25]:
df.shape

(100, 13)

In [27]:
df["price"] = df["price"].str.replace(",", "")

In [29]:
df["rating_nums"] = (
    df["rating_nums"]
    .str.replace(" Ratings", "", regex=False)
    .str.replace("No rating", "0", regex=False)
    .astype("Int64")
)

In [31]:
dtypes = {
    "phone": "string",
    "price": "float64",
    "link": "string",
    "rating": "float64",
    "rating_nums": "Int64",
    "img": "string",
    "desc": "string",
    "specific": "string",
    "delivery": "string",
    "before_discount": "string",
    "ranking": "string",
    "selling_vendor": "string",
    "payment_info": "string",
}

df = df.astype(dtypes)

In [35]:
df.dtypes

phone               string
price              float64
link                string
rating             float64
rating_nums          Int64
img                 string
desc                string
specific            string
delivery            string
before_discount     string
ranking             string
selling_vendor      string
payment_info        string
dtype: object